language: java

jdk:
  - oraclejdk8

sudo: true
install: true

before_script:
 - chmod +x gradlew
 
script:
  - ./gradlew war
  - ./DemoApplicationTests.java
notifications:
  email:
    recipients:
      - zhang.mengf@husky.neu.edu
