language: java

jdk:
  - oraclejdk8

sudo: true
install: true

before_script:
 - chmod +x gradlew
script:
  - ./gradlew war
  - gradle -Dtest.single=DemoApplicationTests test
<<<<<<< HEAD
=======

>>>>>>> 8408d8c075f220f2c814716ca9615dab04c37817
notifications:
  email:
    recipients:
      - zhang.mengf@husky.neu.edu
