language: java

env:
  -DB=mysql
jdk:
  - oraclejdk8
mysql:
  database:csye6225
  username:root
  password:
  encoding:utf8

sudo: true
install: 
   - mvn install -Dmaven.test.skip=true

before_script:
 - chmod +x gradlew
 - cd web              
  - mvn db:create 
  - mvn db:schema  
  - mvn db:data        
  - cd ..
 
script:

  - cd/src/test/java/com/csye6225/demo/ 
  - mvn DemoApplicationTests.java
  - ./gradlew war

notifications:
  email:
    recipients:
      - zhang.mengf@husky.neu.edu
