language: java

jdk:
  - oraclejdk8

sudo: true
install: true

before_script:
 - chmod +x gradlew
 - chmod +x ./src/test/java/com/csye6225/Demo/DemoApplicationTests.java
script:
  - ./gradlew war
  - ./src/test/java/com/csye6225/Demo/DemoApplicationTests.java

notifications:
  email:
    recipients:
      - zhang.mengf@husky.neu.edu
