language: java
jdk:
- oraclejdk8
sudo: false
install: true
before_script:
- chmod +x gradlew
script:
- "./gradlew war"
- gradle -Dtest.single=DemoApplicationTests test
after_success:
- mkdir codedeploy
- zip -r csye6225-fall2017-${TRAVIS_JOB_NUMBER}.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
- ls -al
- mv csye6225-fall2017-${TRAVIS_JOB_NUMBER}.zip codedeploy/
- ls -al
- pwd
- cd codedeploy
- ls -al
- pwd
before_deploy:
- cd ..
deploy:
- provider: s3
  access_key_id: $access_key_id
  deploy.secret_access_key: $secure
  local_dir: codedeploy
  bucket: $bucket
  region: us-east-1
  skip_cleanup: true
  on:
    branch: assignment9
- provider: codedeploy
  access_key_id: $access_key_id
  deploy.secret_access_key: $secure
  bucket: $bucket
  key: csye6225-fall2017-${TRAVIS_JOB_NUMBER}.zip
  bundle_type: zip
  application: csye6225-fall2017
  deployment_group: csye6225-fall2017
  region: us-east-1
  wait-until-deployed: true
  on:
    branch: assignment9