language: java

jdk:
  - oraclejdk8

sudo: true
install: true

before_script:
 - chmod +x gradlew
script:
  - ./gradlew war
  - gradle -Dtest.single=DemoApplicationTests test
notifications:
  email:
    recipients:
      - mengfanxu0802@gmail.com
