language: java

jdk:
  - oraclejdk8

sudo: true
install: true


#deploy:
#  - provider: s3
#  access_key_id: "AKIAJJK3DZ4DJRAQFZRQ"
#  secret_access_key: "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"
#  bucket: "S3 Bucket"
#  skip_cleanup: true
#  - provider: codedeploy
#  access_key_id: "AKIAJJK3DZ4DJRAQFZRQ"
#  secret_access_key: "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"
#  bucket: "S3 Bucket"
#  revision_type: github

before_script:
 - chmod +x gradlew
script:
  - ./gradlew war
  - gradle -Dtest.single=DemoApplicationTests test
notifications:
  email:
    recipients:
      - zhang.mengf@husky.neu.edu
